# Generated by Django 2.0.6 on 2018-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=50, unique=True),
        ),
    ]
